#![no_std]
#![feature(allocator_api)]

extern crate alloc;

pub mod decompress;
pub mod display;
pub mod feed;
pub mod input;
pub mod ns_api;
pub mod persist;
pub mod projection;
pub mod registry;
pub mod train;
pub mod xml_parser;
pub mod zmq;

/// Allocate `len` zeroed bytes in PSRAM and leak the box for a `&'static` borrow.
/// Used for one-shot setup buffers; the tasks run forever so we never reclaim them.
pub fn leak_psram_slice(len: usize) -> &'static mut [u8] {
    let b = alloc::boxed::Box::<[u8], _>::new_uninit_slice_in(len, esp_alloc::ExternalMemory);
    // SAFETY: u8 has no validity invariants; smoltcp/zmq write before reading.
    let b = unsafe { b.assume_init() };
    alloc::boxed::Box::leak(b)
}

/// Log the global heap stats line (internal SRAM + PSRAM regions).
pub fn log_heap_stats() {
    log::info!("heap: {}", esp_alloc::HEAP.stats());
}

/// Compile-time size (in bytes) of the future generated by an
/// `#[embassy_executor::task]` function. Embassy's macro renames the original
/// async fn to `__<name>_task`; that hidden symbol returns
/// `impl Future<Output = ...>` and is what we measure here.
///
/// Example: `task_future_size!(crate::feed::__run_task, Stack<'static>, ...)`.
///
/// Pass the same arg types as the task (no values needed — the function is
/// never invoked, only its return-type size is computed).
#[macro_export]
macro_rules! task_future_size {
    ($task:path $(, $arg_ty:ty)* $(,)?) => {{
        fn _size<F: ::core::future::Future>(_: fn($($arg_ty),*) -> F) -> usize {
            ::core::mem::size_of::<F>()
        }
        _size($task)
    }};
}
